apiVersion: batch/v1
kind: Job
metadata:
  name: myapp 
spec:
  template:
    spec:
      containers:
      - name: pytorch-phy5
        image: gitlab-registry.nrp-nautilus.io/mkhuff/depp/build:v1
        command: 
        - sh
        - -c
        - "cd depp && sleep infinity && python run_core.py data_dir=/depp/cur_data/ gpus=0 patience=2 val_freq=2 min_delta=1e10 run_amount=1 training=False selection=[1,1,1,1,1,1,1,1] && sleep infinity"
        volumeMounts:
        - name: git-repo 
          mountPath: /depp
        resources:
          limits:
            memory: 32Gi
            cpu: "12"
            nvidia.com/gpu: "3"
            ephemeral-storage: 100Gi
          requests:
            memory: 24Gi
            cpu: "12"
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        args:
          - clone
          - https://github.com/MikaelHuff/DEPP
          - /depp 
        volumeMounts:
          - name: git-repo
            mountPath: /depp
      volumes:
      - name: git-repo
        emptyDir: {}
      restartPolicy: Never
      imagePullSecrets:
        - name: secret1
  backoffLimit: 5
