apiVersion: v1
kind: Pod
metadata:
  name: cpu-pod
spec:
  containers:
  - name: pytorch-phy5
    #image: gitlab-registry.nautilus.optiputer.net/mkhuff/nautilus_tutorial/build_tree:v1
    image: gitlab-registry.nrp-nautilus.io/mkhuff/depp/build:v1
    command: ["sh", "-c","mkdir test && cd test && pwd && sleep infinity"]
    resources:
      limits:
        memory: 1Gi
        cpu: "2"
      requests:
        memory: 1Gi
        cpu: "2"
    volumeMounts:
      - name: mydata
        mountPath: /mnt/myscratch
  volumes:
    - name: mydata
      emptyDir: {}
  restartPolicy: Never
  imagePullSecrets:
    - name: secret1
